name: Sync to Hugging Face Hub

on:
  
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Sync with Hugging Face Space
        uses: nateraw/huggingface-sync-action@43d1a88b85777174621c97a58a6fa0293d0c2658
        with:
          
          github_repo_id: 'kelly7y176/Hugging-face-imagenet-classifier-app' 
          

          huggingface_repo_id: 'tyuuu/imagenet-classifier-project'
          hf_token: ${{ secrets.HF_TOKEN }} 
          repo_type: 'space'
          space_sdk: 'gradio'
